-
  type: cohesion_component
  export:
    uuid: d825e699-0505-46d3-a6a0-5dfbbb2da801
    langcode: en
    status: true
    dependencies: {  }
    id: cpt_webform
    label: Webform
    json_values: '{"canvas":[{"type":"container","uid":"container","title":"Container","status":{"collapsed":false},"uuid":"51c9c37d-c36f-4a1c-9c3a-55e8927fb4a5","parentUid":"root","isContainer":true,"children":[{"type":"item","uid":"site_studio_webform_node_element","isCustom":true,"title":"Webform Node Element","selected":false,"status":{"collapsed":true},"uuid":"2c069881-db5c-4a13-9cf3-287f4c5988d5","parentUid":"container","isContainer":false,"children":[]}]}],"componentForm":[{"type":"form-container","uid":"form-section","title":"Field group","status":{"collapsed":false},"options":{"formBuilder":true},"uuid":"89b987e3-6759-441e-b962-3e5e46fcb3dc","parentUid":"root","isContainer":true,"children":[{"type":"form-field","uid":"form-entity-browser","title":"Entity browser","status":{"collapsed":false},"uuid":"1ed197ba-edd9-441e-bb89-19c34d91e849","parentUid":"form-section","isContainer":false,"children":[]}]}],"mapper":{"51c9c37d-c36f-4a1c-9c3a-55e8927fb4a5":{},"2c069881-db5c-4a13-9cf3-287f4c5988d5":{"settings":{"formDefinition":[{"formKey":"site_studio_webform_node_element_settings","children":[{"formKey":"site_studio_webform_node_element_dynamic","breakpoints":[],"activeFields":[{"name":"webform_node_id","active":true}]}]}],"selectorType":"topLevel","form":null,"items":[]}}},"model":{"51c9c37d-c36f-4a1c-9c3a-55e8927fb4a5":{"settings":{"width":"fluid"}},"2c069881-db5c-4a13-9cf3-287f4c5988d5":{"settings":{"title":"Webform Node Element","webform_node_id":"[field.1ed197ba-edd9-441e-bb89-19c34d91e849]"},"context-visibility":{"contextVisibility":{"condition":"ALL"}},"styles":{"settings":{"element":"site_studio_webform_node_element"}}},"89b987e3-6759-441e-b962-3e5e46fcb3dc":{"settings":{"title":"Webform Settings","type":"cohSection","hideRowHeading":0,"removePadding":0,"columnCount":"coh-component-field-group-1-col","breakpointIcon":"","breakpoints":false,"propertiesMenu":false,"disableScrollbar":true,"disableEllipsisMenu":true,"isOpen":true},"contextVisibility":{"condition":"ALL"}},"1ed197ba-edd9-441e-bb89-19c34d91e849":{"settings":{"title":"Webform","type":"cohEntityBrowser","showConfig":false,"hideRowHeading":true,"schema":{"type":"object"},"machineName":"webform","options":{"entityBrowserTypeDisabled":true,"entityTypeDisabled":true,"entityBrowserBundlesDisabled":true,"entityBrowserType":"typeahead","entityType":"node","bundles":{"webform":true}},"entityBrowserTypeTooltipPlacement":"auto right","entityTypeTooltipPlacement":"auto right","entityBrowserTooltipPlacement":"auto right"},"contextVisibility":{"condition":"ALL"},"model":{"value":{"entity":{"entityType":"node"}}}}},"previewModel":{"89b987e3-6759-441e-b962-3e5e46fcb3dc":{},"1ed197ba-edd9-441e-bb89-19c34d91e849":{},"2c069881-db5c-4a13-9cf3-287f4c5988d5":{}},"variableFields":{"89b987e3-6759-441e-b962-3e5e46fcb3dc":[],"1ed197ba-edd9-441e-bb89-19c34d91e849":[],"2c069881-db5c-4a13-9cf3-287f4c5988d5":["settings.webform_node_id"]},"meta":{"fieldHistory":[{"uuid":"1ed197ba-edd9-441e-bb89-19c34d91e849","type":"form-entity-browser","machineName":"webform"}]}}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0029
    locked: false
    modified: true
    selectable: true
    category: cpt_cat_general_components
    preview_image: {  }
    has_quick_edit: true
    entity_type_access: {  }
    bundle_access: {  }
    twig_template: component--cohesion-cpt-webform
    weight: 0
-
  type: cohesion_component_category
  export:
    uuid: f0745755-460f-41c6-a9f9-a67e82e788c4
    langcode: en
    status: true
    dependencies: {  }
    _core:
      default_config_hash: uD3bsqk6dEY_k5T4rq3k_rgjNjR_BC3IXrfvj9t3SKk
    id: cpt_cat_general_components
    label: 'General components'
    json_values: '{}'
    json_mapper: '{}'
    last_entity_update: entityupdate_0029
    locked: false
    modified: false
    selectable: true
    class: category-3
    weight: -10
